[package]
name = "wshowkeys_rs"
version = "1.1.0"
edition = "2021"
authors = ["isomo <jiahaoxiang2000@gmail.com>"]
description = "A Rust implementation of wshowkeys - displays keystrokes on screen for Wayland"
license = "GPL-3.0"
keywords = ["wayland", "keylogger", "display", "input"]
categories = ["multimedia", "gui"]
